#!/usr/bin/env bash
# install nginx on web-01 
# nginx is listenig to port 80
apt-get update
apt-get install -y nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World" > /etc/nginx/html/index.html
printf %s "server {
        root        /etc/nginx/html;
        index       index.html index.htm;
        listen      80 default_server;
        listen      [::]:80 default_server;
}
" > /etc/nginx/sites-available/default
service nginx restart
