#!/usr/bin/env bash
# installs nginx svr and configures it to listen on port 80
sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
