#!/usr/bin/env bash
#configure the nginx server to have a custom 404 page Ceci n'est pas une page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/liesten 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee file /var/www/html/404.html
sudo sed -i "/server_name _;/a error_page 404 /404.html;\nlocation = /404.html {\nroot /var/www/html;\ninternal;\n}" /etc/nginx/sites-available/default
sudo service nginx restart
