#!/usr/bin/env bash
#Install and configure HAproxy on ypour lb-01
#Configure HAproxy so that it sends traffic to
#web-01 and web-02

#Update packages
sudo apt-get -y update
sudo apt-get -y upgrade

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

#Install HAProxy
sudo apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$lbalancer" >> /etc/haproxy/haproxy.cfg

lbalancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 166828-web-01 100.26.222.47:80 check
    server 166828-web-02 52.90.22.130:80 check
"
sudo service haproxy restart
