#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

 #listen load_balancer
echo "
frontend my_file
   bind *:80
   mode http
   default_backend backend_file

backend backend_file
   balance roundrobin
   server 167419-web-01 35.174.211.234:80 check
   server 167419-web-02 100.25.141.83:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
