#!/usr/bin/env bash
# implementing the script 101-manage_my_process that manages the manage_my_process by using inputs start, restart and stop
if [ "$1" = "start" ]; then
    ./manage_my_process &
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "$1" = "stop" ]; then
    kill "$(pgrep -f /manage_my_process)"
    sudo rm /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [ "$1" = "restart" ]; then
    kill "$(pgrep -f /manage_my_process)"
    sudo rm /var/run/my_process.pid
    ./manage_my_process &
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi

