#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
# display hours from 0 to 12
# display minutes from 1 to 59
HOURS=0
while [ "${HOURS}" -lt 13 ];do
    MINUTS=1
    echo "Hour: ${HOURS}"
    while [ "${MINUTS}" -lt 60 ];do
        echo "${MINUTS}"
        MINUTS=$(( MINUTS + 1 ))
    done
    HOURS=$(( HOURS + 1 ))
done
