#!/usr/bin/env bash
# gives information about the school file.
TEST_FILE="school"
if [ -e "${TEST_FILE}" ];then
    echo "${TEST_FILE} file exists"
    if [ -s "${TEST_FILE}" ];then
        echo "${TEST_FILE} file is not empty"
    else
        echo "${TEST_FILE} file is empty"
    fi
    if [ -f "${TEST_FILE}" ];then
        echo "${TEST_FILE} is a regular file"
    fi
else
    echo "${TEST_FILE} file does not exist"
fi
