#!/usr/bin/env bash
# Configures an Ubuntu server with specific requirements

cp /etc/hosts ~/hosts.old

echo "127.0.0.2 localhost" > ~/hosts.old
echo "8.8.8.8 facebook.com" >> ~/hosts.old
cp -f ~/hosts.old /etc/hosts
